### ISSUE TITLE
Spin App::pwhich off of this dist

### ISSUE THREAD

**Issue by plicease** [plicease/File-Which#1]
Reported here:

https://rt.cpan.org/Ticket/Display.html?id=94757
https://rt.cpan.org/Ticket/Display.html?id=94758
https://rt.cpan.org/Ticket/Display.html?id=99378

This is my plan of attack:
- the guts of `script/pwhich` has already been moved into `lib/App/pwhich.pm` and will be included with version 1.10.
- shortly after that another release (perhaps <strike>1.11</strike> 1.14) will be released with `File-Which` and `App-pwhich` as separate dists.
  - Both `File-Which` and `App-pwhich` in the next version will come with a version of `script/pwhich`, but the one bundled with `File-Which` will issue a deprecation warning.
- The tests that use `Test::Scrpt` in the next version will become optional in the `File-Which` dist.
- April 30, 2015 or later I will release a version of `File-Which` with the deprecated `script/pwhich` removed, along with the tests that depend on `Test::Script`.

If anyone has any reservations as to this approach please let me know ASAP.

**Comment by plicease** [comment]
This morning I pushed out version 1.14 of `File-Which` and `App-pwhich`.

**Comment by dolmen** [comment]
Cc: @dolmen (reporter of the RT tickets)

Blog post: http://blogs.perl.org/users/graham_ollis/2015/03/filewhich-pwhich-and-apppwhich.html

**Comment by plicease** [comment]
Fixed in 1.17
