### ISSUE TITLE
File::Which on Windows

### ISSUE THREAD

**Issue by howi42** [plicease/File-Which#12]
I installed File::Which via cpan, but still get this message :
'which' is not recognized as an internal or external command,
operable program or batch file.

How can I investigate this further ?

The only place I find 'Which' listed, is under C://Strawberry/perl/vendor/lib/File
but that is not part of the PATH-variable

**Comment by plicease** [comment]
`File::Which` no longer comes bundled with the command line `which` interface, this is just the Perl API for which.  For that you can install `App::pwhich`, although the command is `pwhich` so as not to conflict with the OS `which` on platforms that provide it.  You may also want to consider the GNU Win32 port of which:

http://gnuwin32.sourceforge.net/packages/which.htm
