### ISSUE TITLE
Tests are not skipped if Test::Script is missing

### ISSUE THREAD

**Issue by eserte** [plicease/File-Which#3]
See http://www.cpantesters.org/cpan/report/a4fa6370-d607-11e4-b221-9e126cbd7f71 for a sample fail report. It seems that only t/01_compile_script.t is correctly skipped if Test::Script is missing, but three other test files are not.

**Comment by plicease** [comment]
This should be fixed in 1.16.

**Comment by eserte** [comment]
It is, thanks!
