### ISSUE TITLE
Test failing with Strawberry Perl

### ISSUE THREAD

**Issue by Arenlor** [plicease/File-Which#9]
`$ make test`
`PERL_DL_NONLAZY=1 "/usr/bin/perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t`
`t/00_diag.t ..... 1/1 #`
`#`
`#`
`# HARNESS_ACTIVE=1`
`# HARNESS_VERSION=3.36_01`
`# LANG=en_US.UTF-8`
`# PERL5LIB=/c/Users/arenlor/.cpanm/work/1504814909.18756/File-Which-1.21/blib/lib:/c/Users/arenlor/.cpanm/work/1504814909.18756/File-Which-1.21/blib/arch`
`# PERL_DL_NONLAZY=1`
`# SHELL=/usr/bin/bash.exe`
`#`
`#`
`#`
`# PERL5LIB path`
`# /c/Users/arenlor/.cpanm/work/1504814909.18756/File-Which-1.21/blib/lib`
`# /c/Users/arenlor/.cpanm/work/1504814909.18756/File-Which-1.21/blib/arch`
`#`
`#`
`#`
`# perl                5.024001`
`# ExtUtils::MakeMaker 7.1002`
`# Test::More          1.001014`
`#`
`#`
`#`
`t/00_diag.t ..... ok`
`t/01_compile.t .. ok`
`t/02_all.t ...... 1/6 Use of uninitialized value $zero in concatenation (.) or string at t/02_all.t line 39.`

`#   Failed test 'zero = '`
`#   at t/02_all.t line 39.`
`# Looks like you failed 1 test of 6.`
`t/02_all.t ...... Dubious, test returned 1 (wstat 256, 0x100)`
`Failed 1/6 subtests`
`t/03_simple.t ... ok`
`t/04_pwhich.t ... ok`

`Test Summary Report`
`-------------------`
`t/02_all.t    (Wstat: 256 Tests: 6 Failed: 1)`
`  Failed test:  5`
`  Non-zero exit status: 1`
`Files=5, Tests=21,  1 wallclock secs ( 0.00 usr  0.09 sys +  0.23 cusr  0.29 csys =  0.62 CPU)`
`Result: FAIL`
`Failed 1/5 test programs. 1/21 subtests failed.`
`make: *** [Makefile:838: test_dynamic] Error 255`

**Comment by plicease** [comment]
That doesn't look like strawberry Perl.  Are you sure you aren't using MSYS or MinGW?

If you can provide the output from: 

```
perl -V
```

and

```
prove -bvm t/02_all.t
```

that would help.

**Comment by plicease** [comment]
I confirmed that I was able to reproduce this with MSYS2.  I also realized that I a had already fixed this back in May, but hadn't done a release.  I've now dispatched this fix as 1.22 to cpan.
